//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SMCHDBModel", "FK_InitiateMemberInfos_EmploymentStatus", "EmploymentStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SMCHSGManager.Models.EmploymentStatus), "OrdinaryMemberInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMCHSGManager.Models.OrdinaryMemberInfo), true)]
[assembly: EdmRelationshipAttribute("SMCHDBModel", "FK_InitiateMemberInfos_Nationalities", "Nationalities", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SMCHSGManager.Models.Nationality), "OrdinaryMemberInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMCHSGManager.Models.OrdinaryMemberInfo), true)]
[assembly: EdmRelationshipAttribute("SMCHDBModel", "FK_InitiateMemberInfos_Races", "Races", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SMCHSGManager.Models.Race), "OrdinaryMemberInfos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMCHSGManager.Models.OrdinaryMemberInfo), true)]

#endregion

namespace SMCHSGManager.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SMCHDBLocalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SMCHDBLocalEntities object using the connection string found in the 'SMCHDBLocalEntities' section of the application configuration file.
        /// </summary>
        public SMCHDBLocalEntities() : base("name=SMCHDBLocalEntities", "SMCHDBLocalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMCHDBLocalEntities object.
        /// </summary>
        public SMCHDBLocalEntities(string connectionString) : base(connectionString, "SMCHDBLocalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMCHDBLocalEntities object.
        /// </summary>
        public SMCHDBLocalEntities(EntityConnection connection) : base(connection, "SMCHDBLocalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmploymentStatus> EmploymentStatuses
        {
            get
            {
                if ((_EmploymentStatuses == null))
                {
                    _EmploymentStatuses = base.CreateObjectSet<EmploymentStatus>("EmploymentStatuses");
                }
                return _EmploymentStatuses;
            }
        }
        private ObjectSet<EmploymentStatus> _EmploymentStatuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Nationality> Nationalities
        {
            get
            {
                if ((_Nationalities == null))
                {
                    _Nationalities = base.CreateObjectSet<Nationality>("Nationalities");
                }
                return _Nationalities;
            }
        }
        private ObjectSet<Nationality> _Nationalities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrdinaryMemberInfo> OrdinaryMemberInfos
        {
            get
            {
                if ((_OrdinaryMemberInfos == null))
                {
                    _OrdinaryMemberInfos = base.CreateObjectSet<OrdinaryMemberInfo>("OrdinaryMemberInfos");
                }
                return _OrdinaryMemberInfos;
            }
        }
        private ObjectSet<OrdinaryMemberInfo> _OrdinaryMemberInfos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Race> Races
        {
            get
            {
                if ((_Races == null))
                {
                    _Races = base.CreateObjectSet<Race>("Races");
                }
                return _Races;
            }
        }
        private ObjectSet<Race> _Races;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmploymentStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmploymentStatuses(EmploymentStatus employmentStatus)
        {
            base.AddObject("EmploymentStatuses", employmentStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Nationalities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNationalities(Nationality nationality)
        {
            base.AddObject("Nationalities", nationality);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrdinaryMemberInfos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrdinaryMemberInfos(OrdinaryMemberInfo ordinaryMemberInfo)
        {
            base.AddObject("OrdinaryMemberInfos", ordinaryMemberInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Races EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRaces(Race race)
        {
            base.AddObject("Races", race);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMCHDBModel", Name="EmploymentStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmploymentStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmploymentStatus object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static EmploymentStatus CreateEmploymentStatus(global::System.Int32 id, global::System.String name)
        {
            EmploymentStatus employmentStatus = new EmploymentStatus();
            employmentStatus.ID = id;
            employmentStatus.Name = name;
            return employmentStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MemberFee
        {
            get
            {
                return _MemberFee;
            }
            set
            {
                OnMemberFeeChanging(value);
                ReportPropertyChanging("MemberFee");
                _MemberFee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberFee");
                OnMemberFeeChanged();
            }
        }
        private Nullable<global::System.Decimal> _MemberFee;
        partial void OnMemberFeeChanging(Nullable<global::System.Decimal> value);
        partial void OnMemberFeeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMCHDBModel", "FK_InitiateMemberInfos_EmploymentStatus", "OrdinaryMemberInfos")]
        public EntityCollection<OrdinaryMemberInfo> OrdinaryMemberInfos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrdinaryMemberInfo>("SMCHDBModel.FK_InitiateMemberInfos_EmploymentStatus", "OrdinaryMemberInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrdinaryMemberInfo>("SMCHDBModel.FK_InitiateMemberInfos_EmploymentStatus", "OrdinaryMemberInfos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMCHDBModel", Name="Nationality")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Nationality : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Nationality object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Nationality CreateNationality(global::System.Int32 id, global::System.String name)
        {
            Nationality nationality = new Nationality();
            nationality.ID = id;
            nationality.Name = name;
            return nationality;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMCHDBModel", "FK_InitiateMemberInfos_Nationalities", "OrdinaryMemberInfos")]
        public EntityCollection<OrdinaryMemberInfo> OrdinaryMemberInfos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrdinaryMemberInfo>("SMCHDBModel.FK_InitiateMemberInfos_Nationalities", "OrdinaryMemberInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrdinaryMemberInfo>("SMCHDBModel.FK_InitiateMemberInfos_Nationalities", "OrdinaryMemberInfos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMCHDBModel", Name="OrdinaryMemberInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrdinaryMemberInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrdinaryMemberInfo object.
        /// </summary>
        /// <param name="iMemberID">Initial value of the IMemberID property.</param>
        public static OrdinaryMemberInfo CreateOrdinaryMemberInfo(global::System.Guid iMemberID)
        {
            OrdinaryMemberInfo ordinaryMemberInfo = new OrdinaryMemberInfo();
            ordinaryMemberInfo.IMemberID = iMemberID;
            return ordinaryMemberInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IMemberID
        {
            get
            {
                return _IMemberID;
            }
            set
            {
                if (_IMemberID != value)
                {
                    OnIMemberIDChanging(value);
                    ReportPropertyChanging("IMemberID");
                    _IMemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IMemberID");
                    OnIMemberIDChanged();
                }
            }
        }
        private global::System.Guid _IMemberID;
        partial void OnIMemberIDChanging(global::System.Guid value);
        partial void OnIMemberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameInNative
        {
            get
            {
                return _NameInNative;
            }
            set
            {
                OnNameInNativeChanging(value);
                ReportPropertyChanging("NameInNative");
                _NameInNative = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameInNative");
                OnNameInNativeChanged();
            }
        }
        private global::System.String _NameInNative;
        partial void OnNameInNativeChanging(global::System.String value);
        partial void OnNameInNativeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NationalityID
        {
            get
            {
                return _NationalityID;
            }
            set
            {
                OnNationalityIDChanging(value);
                ReportPropertyChanging("NationalityID");
                _NationalityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NationalityID");
                OnNationalityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _NationalityID;
        partial void OnNationalityIDChanging(Nullable<global::System.Int32> value);
        partial void OnNationalityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RaceID
        {
            get
            {
                return _RaceID;
            }
            set
            {
                OnRaceIDChanging(value);
                ReportPropertyChanging("RaceID");
                _RaceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RaceID");
                OnRaceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RaceID;
        partial void OnRaceIDChanging(Nullable<global::System.Int32> value);
        partial void OnRaceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmploymentStatusID
        {
            get
            {
                return _EmploymentStatusID;
            }
            set
            {
                OnEmploymentStatusIDChanging(value);
                ReportPropertyChanging("EmploymentStatusID");
                _EmploymentStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmploymentStatusID");
                OnEmploymentStatusIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EmploymentStatusID;
        partial void OnEmploymentStatusIDChanging(Nullable<global::System.Int32> value);
        partial void OnEmploymentStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlaceOfInitiation
        {
            get
            {
                return _PlaceOfInitiation;
            }
            set
            {
                OnPlaceOfInitiationChanging(value);
                ReportPropertyChanging("PlaceOfInitiation");
                _PlaceOfInitiation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlaceOfInitiation");
                OnPlaceOfInitiationChanged();
            }
        }
        private global::System.String _PlaceOfInitiation;
        partial void OnPlaceOfInitiationChanging(global::System.String value);
        partial void OnPlaceOfInitiationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NRICOrFINNo
        {
            get
            {
                return _NRICOrFINNo;
            }
            set
            {
                OnNRICOrFINNoChanging(value);
                ReportPropertyChanging("NRICOrFINNo");
                _NRICOrFINNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NRICOrFINNo");
                OnNRICOrFINNoChanged();
            }
        }
        private global::System.String _NRICOrFINNo;
        partial void OnNRICOrFINNoChanging(global::System.String value);
        partial void OnNRICOrFINNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MemberApplyDate
        {
            get
            {
                return _MemberApplyDate;
            }
            set
            {
                OnMemberApplyDateChanging(value);
                ReportPropertyChanging("MemberApplyDate");
                _MemberApplyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberApplyDate");
                OnMemberApplyDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MemberApplyDate;
        partial void OnMemberApplyDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMemberApplyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MemberEffectiveStartDate
        {
            get
            {
                return _MemberEffectiveStartDate;
            }
            set
            {
                OnMemberEffectiveStartDateChanging(value);
                ReportPropertyChanging("MemberEffectiveStartDate");
                _MemberEffectiveStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberEffectiveStartDate");
                OnMemberEffectiveStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MemberEffectiveStartDate;
        partial void OnMemberEffectiveStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMemberEffectiveStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MemberFeePayByID
        {
            get
            {
                return _MemberFeePayByID;
            }
            set
            {
                OnMemberFeePayByIDChanging(value);
                ReportPropertyChanging("MemberFeePayByID");
                _MemberFeePayByID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberFeePayByID");
                OnMemberFeePayByIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MemberFeePayByID;
        partial void OnMemberFeePayByIDChanging(Nullable<global::System.Int32> value);
        partial void OnMemberFeePayByIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Occupation
        {
            get
            {
                return _Occupation;
            }
            set
            {
                OnOccupationChanging(value);
                ReportPropertyChanging("Occupation");
                _Occupation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Occupation");
                OnOccupationChanged();
            }
        }
        private global::System.String _Occupation;
        partial void OnOccupationChanging(global::System.String value);
        partial void OnOccupationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EducationLevel
        {
            get
            {
                return _EducationLevel;
            }
            set
            {
                OnEducationLevelChanging(value);
                ReportPropertyChanging("EducationLevel");
                _EducationLevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EducationLevel");
                OnEducationLevelChanged();
            }
        }
        private global::System.String _EducationLevel;
        partial void OnEducationLevelChanging(global::System.String value);
        partial void OnEducationLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpecialSkill
        {
            get
            {
                return _SpecialSkill;
            }
            set
            {
                OnSpecialSkillChanging(value);
                ReportPropertyChanging("SpecialSkill");
                _SpecialSkill = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SpecialSkill");
                OnSpecialSkillChanged();
            }
        }
        private global::System.String _SpecialSkill;
        partial void OnSpecialSkillChanging(global::System.String value);
        partial void OnSpecialSkillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMCHDBModel", "FK_InitiateMemberInfos_EmploymentStatus", "EmploymentStatuses")]
        public EmploymentStatus EmploymentStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmploymentStatus>("SMCHDBModel.FK_InitiateMemberInfos_EmploymentStatus", "EmploymentStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmploymentStatus>("SMCHDBModel.FK_InitiateMemberInfos_EmploymentStatus", "EmploymentStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EmploymentStatus> EmploymentStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmploymentStatus>("SMCHDBModel.FK_InitiateMemberInfos_EmploymentStatus", "EmploymentStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EmploymentStatus>("SMCHDBModel.FK_InitiateMemberInfos_EmploymentStatus", "EmploymentStatuses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMCHDBModel", "FK_InitiateMemberInfos_Nationalities", "Nationalities")]
        public Nationality Nationality
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nationality>("SMCHDBModel.FK_InitiateMemberInfos_Nationalities", "Nationalities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nationality>("SMCHDBModel.FK_InitiateMemberInfos_Nationalities", "Nationalities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nationality> NationalityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nationality>("SMCHDBModel.FK_InitiateMemberInfos_Nationalities", "Nationalities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nationality>("SMCHDBModel.FK_InitiateMemberInfos_Nationalities", "Nationalities", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMCHDBModel", "FK_InitiateMemberInfos_Races", "Races")]
        public Race Race
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("SMCHDBModel.FK_InitiateMemberInfos_Races", "Races").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("SMCHDBModel.FK_InitiateMemberInfos_Races", "Races").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Race> RaceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("SMCHDBModel.FK_InitiateMemberInfos_Races", "Races");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Race>("SMCHDBModel.FK_InitiateMemberInfos_Races", "Races", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMCHDBModel", Name="Race")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Race : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Race CreateRace(global::System.Int32 id, global::System.String name)
        {
            Race race = new Race();
            race.ID = id;
            race.Name = name;
            return race;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMCHDBModel", "FK_InitiateMemberInfos_Races", "OrdinaryMemberInfos")]
        public EntityCollection<OrdinaryMemberInfo> OrdinaryMemberInfos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrdinaryMemberInfo>("SMCHDBModel.FK_InitiateMemberInfos_Races", "OrdinaryMemberInfos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrdinaryMemberInfo>("SMCHDBModel.FK_InitiateMemberInfos_Races", "OrdinaryMemberInfos", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
