//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainMenu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be Veg,.
        /// </summary>
        internal static string BeVeg {
            get {
                return ResourceManager.GetString("BeVeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European Time.
        /// </summary>
        internal static string CET {
            get {
                return ResourceManager.GetString("CET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Green.
        /// </summary>
        internal static string GoGreen {
            get {
                return ResourceManager.GetString("GoGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live TV.
        /// </summary>
        internal static string LiveTV {
            get {
                return ResourceManager.GetString("LiveTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule:.
        /// </summary>
        internal static string NextSchedule {
            get {
                return ResourceManager.GetString("NextSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please join us to meditate for World Vegan &amp; World Peace.
        /// </summary>
        internal static string PleaseJoinUs {
            get {
                return ResourceManager.GetString("PleaseJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Save the Planet !.
        /// </summary>
        internal static string SavethePlanet {
            get {
                return ResourceManager.GetString("SavethePlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTV Shows.
        /// </summary>
        internal static string SMTVShows {
            get {
                return ResourceManager.GetString("SMTVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTV on YouTube.
        /// </summary>
        internal static string SMTVYT {
            get {
                return ResourceManager.GetString("SMTVYT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Vegan, World Peace.
        /// </summary>
        internal static string TitleSlogan {
            get {
                return ResourceManager.GetString("TitleSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos Manager.
        /// </summary>
        internal static string VideoManager {
            get {
                return ResourceManager.GetString("VideoManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Group Meditation Hours.
        /// </summary>
        internal static string WorldMeditaionHours {
            get {
                return ResourceManager.GetString("WorldMeditaionHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Local Time.
        /// </summary>
        internal static string YourTime {
            get {
                return ResourceManager.GetString("YourTime", resourceCulture);
            }
        }
    }
}
